### ISSUE TITLE
Infinity点を獲得した際にランキングに登録されない

### ISSUE THREAD

**Issue by kamesan1577** [Shiryu-Toujima-1f10210346/NextGPT#35]
### Describe the bug

クエリーにnullが代入されるためbad requestがかえってくる

### To Reproduce

1. デバッグページに飛ぶ
2. scoreにInfinityを入力
3. ランキング更新を押下

### OS

Ubuntu

### Node version

v16.20.1

**Comment by Shiryu-Toujima-1f10210346** [comment]
Infinity点とれてすごいね～
